name: h_enterprise
description: H Enterprise official business website.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animations: ^2.0.8
  fluentui_system_icons: ^1.1.221
  google_fonts: ^5.1.0
  carousel_slider: ^4.2.1
  scaled_list: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0




flutter:
  uses-material-design: true
  assets:
    - web/assets/fonts/MaterialIcons-Regular.ttf
    - lib/assets/1.jpg
    - lib/assets/IoT.png
    - lib/assets/plumbing.jpeg
    - lib/assets/wiring.jpg
